added new page with all the reservations of an user
zulu607i/Cinema pull request #13
Opened 2022-06-14 12:16 UTC by zulu607i

2022-06-14 12:27 UTC, drejleeo requested changes

2022-06-14 12:27 UTC, drejleeo commented on reservation/views.py
> +def get_csv_file(request, pk):
Currently, the view is accessible by anyone; if I know the id of an user, i can get a csv with his reservations. Allow only logged in users to get their reservations without providing the id as a parameter. Get the logged in user automatically, no parameters.

2022-06-14 15:57 UTC, drejleeo approved these changes

2022-06-15 06:42 UTC, maxinasa approved these changes

2022-06-15 06:49 UTC, merged